In [1]:
from matplotlib import pyplot
import numpy
%matplotlib inline
from matplotlib import rcParams
rcParams['font.family'] = 'serif'
rcParams['font.size'] = 16

In [2]:
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

In [3]:
def plot_3D(x, y, p):
    '''Creates 3D plot with appropriate limits and viewing angle
    
    Parameters:
    ----------
    x: array of float
        nodal coordinates in x
    y: array of float
        nodal coordinates in y
    p: 2D array of float
        calculated potential field
    
    '''
    fig = pyplot.figure(figsize=(11,7), dpi=100)
    ax = fig.gca(projection='3d') #If fig is a variable holding a figure, fig.gca() 
    #returns the axes associated with the figure. If there’s a projection=… argument to gca,
    #the axes returned are those tagged with the indicated tag (which is commonly a string, 
    #but can be an instance of a projection class).
    X,Y = numpy.meshgrid(x,y) #crea los vectores X e Y que corresponden a la malla
    surf = ax.plot_surface(X,Y,p[:], rstride=1, cstride=1, cmap=cm.viridis,
            linewidth=0, antialiased=False)

    ax.set_xlim(0,1)
    ax.set_ylim(0,1)
    ax.set_xlabel('$x$')
    ax.set_ylabel('$y$')
    ax.set_zlabel('$z$')
    ax.view_init(30,45)


In [4]:
def p_analytical(x, y):
    X, Y = numpy.meshgrid(x,y)
    
    p_an = numpy.sinh(1.5*numpy.pi*Y / x[-1]) /\
    (numpy.sinh(1.5*numpy.pi*y[-1]/x[-1]))*numpy.sin(1.5*numpy.pi*X/x[-1])
    
    return p_an

In [15]:
nx = 3
ny = 3

x = numpy.linspace(0,1,nx) #Return evenly spaced numbers over a specified interval.
y = numpy.linspace(0,1,ny) #equivalente a np.linspace

p_an = p_analytical(x,y)

In [16]:
print(x)

[ 0.   0.5  1. ]


In [17]:
print(y)

[ 0.   0.5  1. ]


In [18]:
print(p_an)

[[ 0.          0.         -0.        ]
 [ 0.          0.06642304 -0.09393637]
 [ 0.          0.70710678 -1.        ]]


In [21]:
X, Y = numpy.meshgrid(x,y)

In [22]:
X

array([[ 0. ,  0.5,  1. ],
       [ 0. ,  0.5,  1. ],
       [ 0. ,  0.5,  1. ]])

In [23]:
Y

array([[ 0. ,  0. ,  0. ],
       [ 0.5,  0.5,  0.5],
       [ 1. ,  1. ,  1. ]])

In [24]:
p_an[:]

array([[ 0.        ,  0.        , -0.        ],
       [ 0.        ,  0.06642304, -0.09393637],
       [ 0.        ,  0.70710678, -1.        ]])

In [25]:
p_an[:,:]

array([[ 0.        ,  0.        , -0.        ],
       [ 0.        ,  0.06642304, -0.09393637],
       [ 0.        ,  0.70710678, -1.        ]])